### ISSUE TITLE
custom CSS on top of default CSS

### ISSUE THREAD

**Issue by wivaku** [BlueHatbRit/mdpdf#44] opened 2018-06-05 11:08 UTC
It is possible to use your own CSS.
Current situation: custom CSS replaces default CSS, see https://github.com/BlueHatbRit/mdpdf/issues/13
Would be great if there can be an option to use the custom CSS **on top** of the default CSS.

Until then I use the workaround: dowload the [default CSS file](https://github.com/BlueHatbRit/mdpdf/blob/master/assets/github-markdown-css.css) and modify it.

**Comment by BlueHatbRit** [comment] 2018-06-05 13:30
Hi @wivaku, thanks for the question, are you using the CLI or the API?

**Comment by wivaku** [comment] 2018-06-05 13:30
the CLI

**Comment by BlueHatbRit** [comment] 2018-06-05 14:18
The default styles you'll be seeing are the github markdown styles, which means this is a duplicate of #34 asking for the ability to keep github styles when adding custom ones as you've asked for.

If you'd like to thumbs up the original post on there, or maybe even submit a PR that would be fantastic. It's only me on the project at the moment so my time is quite limited but I will get to it when I can, though it might be a little while.

For now, as you said a workaround is to pull the github markdown css and use that as your base.

**Comment by wivaku** [comment] 2018-06-05 14:20
ah, sorry for missing #34 . Thanks for the prompt replies

**Closed** 2018-06-05 14:19 UTC

**Comment by BlueHatbRit** [comment] 2018-06-05 14:26
It's all good, no worries at all. I am active here, I just have limited time to dev on it all around work. Any contributions are much appreciated, including bug reports / feature requests!
